allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.60.1 || 8.65.0'
  - '@typescript-eslint/parser@8.60.1 || 8.65.0'
  - '@typescript-eslint/project-service@8.60.1 || 8.65.0'
  - '@typescript-eslint/scope-manager@8.60.1 || 8.65.0'
  - '@typescript-eslint/tsconfig-utils@8.60.1 || 8.65.0'
  - '@typescript-eslint/type-utils@8.60.1 || 8.65.0'
  - '@typescript-eslint/types@8.60.1 || 8.65.0'
  - '@typescript-eslint/typescript-estree@8.60.1 || 8.65.0'
  - '@typescript-eslint/utils@8.60.1 || 8.65.0'
  - '@typescript-eslint/visitor-keys@8.60.1 || 8.65.0'
  - typescript-eslint@8.60.1 || 8.65.0
  - '@vitest/coverage-istanbul@4.1.9'
  - '@vitest/expect@4.1.9'
  - '@vitest/mocker@4.1.9'
  - '@vitest/pretty-format@4.1.9'
  - '@vitest/runner@4.1.9'
  - '@vitest/snapshot@4.1.9'
  - '@vitest/spy@4.1.9'
  - '@vitest/ui@4.1.9'
  - '@vitest/utils@4.1.9'
  - vitest@4.1.9
  - prettier@3.9.6
